sonar.projectKey=web-crawler-api
sonar.projectName=Web Crawler API
sonar.sources=crawler-api/src,crates/crawler-config/src,crates/crawler-domain/src
sonar.tests=crawler-api/tests
sonar.rust.cargo.manifestPaths=crawler-api/Cargo.toml,crates/crawler-config/Cargo.toml,crates/crawler-domain/Cargo.toml
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=target/sonar-clippy.json
sonar.rust.lcov.reportPaths=target/sonar-api-rust-lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/test-results/**
